; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = seeed_xiao_esp32c6
;default_envs = esp32dev
;default_envs = esp32dev_voice_offline
;default_envs = esp12e
;default_envs = esp01
;default_envs = esp8285
;default_envs =  wemos_d1_R2
;default_envs = esp8266_d1_mini
;default_envs = esp01_1m
;default_envs = Shelly_1L


[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32.git
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
; Indica o arquivo de partições com suporte a Zigbee
board_build.partitions = partitions.csv
build_flags = 
    -D CORE_DEBUG_LEVEL=1
    -D ZIGBEE_MODE_ED
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    ; Direciona o linker para a pasta de bibliotecas compiladas do ESP32-C6
    -L "${platformio.packages_dir}/framework-arduinoespressif32-libs/esp32c6/lib"
    ; Vincula os arquivos estáticos específicos do modo End Device (.ed)
    -l esp_zb_api.ed
    -l zboss_stack.ed
    -l zboss_port.native